/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_vinetech_util_crypt_CryptHelper */

#ifndef _Included_com_vinetech_util_crypt_CryptHelper
#define _Included_com_vinetech_util_crypt_CryptHelper
#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     com_galuster_util_crypt_CryptHelper
 * Method:    getKey
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_vinetech_util_crypt_CryptHelper_getKey
  (JNIEnv *, jobject);

/*
 * Class:     com_galuster_util_crypt_CryptHelper
 * Method:    toHashCryptKey
 * Signature: (II)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_vinetech_util_crypt_CryptHelper_toHashCryptKey
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
